"""
Aria Ambient Intelligence - Actors

Actors prepare actions based on insights generated by the cortex.
They don't execute actions automatically - they prepare drafts, suggestions,
and responses for user approval.

Available Actors:
- Actor: Base class for all actors
- ActorConfig: Configuration for actors
- ContentDrafter: Drafts social posts, articles, responses
- AlertComposer: Composes notifications and alerts
"""

from .base import Actor, ActorConfig
from .content import ContentDrafter
from .alert import AlertComposer

__all__ = [
    "Actor",
    "ActorConfig",
    "ContentDrafter",
    "AlertComposer",
]
